version: '3'
services:
  #Administration Api
  promocode-factory-administration-api:
    build: src/Otus.Teaching.Pcf.Administration/
    container_name: 'promocode-factory-administration-api'
    restart: always
    ports:
      - "8091:80"
    environment:
      - "ConnectionStrings:PromocodeFactoryAdministrationDb=Host=promocode-factory-administration-db;Database=promocode_factory_administration_db;Username=postgres;Password=docker"          
    depends_on: 
      - promocode-factory-administration-db
      
  #Administration Db
  promocode-factory-administration-db:
    image: "postgres:15.7"
    container_name: 'promocode-factory-administration-db'
    restart: always 
    ports:
      - 5433:5432
    environment: 
      - POSTGRES_PASSWORD=docker
    volumes:
      - promocode-factory-administration-db-data:/var/lib/postgresql/data

  #ReceivingFromPartner Api
  promocode-factory-receiving-from-partner-api:
    build: src/Otus.Teaching.Pcf.ReceivingFromPartner/
    container_name: 'promocode-factory-receiving-from-partner-api'
    restart: always
    ports:
      - "8092:80"
    environment:
      - "ConnectionStrings:PromocodeFactoryReceivingFromPartnerDb=Host=promocode-factory-receiving-from-partner-db;Database=promocode_factory_receiving_from_partner_db;Username=postgres;Password=docker"
      - "IntegrationSettings:GivingToCustomerApiUrl=http://promocode-factory-giving-to-customer-api"    
      - "IntegrationSettings:AdministrationApiUrl=http://promocode-factory-administration-api"       
    depends_on: 
      - promocode-factory-receiving-from-partner-db

  #ReceivingFromPartner Db
  promocode-factory-receiving-from-partner-db:
    image: "postgres:15.7"
    container_name: 'promocode-factory-receiving-from-partner-db'
    restart: always 
    ports:
      - 5434:5432
    environment: 
      - POSTGRES_PASSWORD=docker
    volumes:
      - promocode-factory-receiving-from-partner-db-data:/var/lib/postgresql/data
  
  #GivingToCustomer Api
  promocode-factory-giving-to-customer-api:
    build: src/Otus.Teaching.Pcf.GivingToCustomer/
    container_name: 'promocode-factory-giving-to-customer-api'
    restart: always
    ports:
      - "8093:80"
    environment:
      - "ConnectionStrings:PromocodeFactoryGivingToCustomerDb=Host=promocode-factory-giving-to-customer-db;Database=promocode_factory_giving_to_customer_db;Username=postgres;Password=docker"          
    depends_on: 
      - promocode-factory-giving-to-customer-db

  #GivingToCustomer Db
  promocode-factory-giving-to-customer-db:
    image: "postgres:15.7"
    container_name: 'promocode-factory-giving-to-customer-db'
    restart: always 
    ports:
      - 5435:5432
    environment: 
      - POSTGRES_PASSWORD=docker
    volumes:
      - promocode-factory-giving-to-customer-db-data:/var/lib/postgresql/data

  #RabbitMQ
  promocode-factory-rabbitmq:
    image: rabbitmq:management-alpine 
    container_name: promocode-factory-rabbitmq
    restart: always 
    ports:
      - "5672:5672"  
      - "15672:15672"  
    hostname: pfc
    environment:
      RABBITMQ_DEFAULT_USER: pfc_admin  
      RABBITMQ_DEFAULT_PASS: pfc_admin    
    volumes:
      - promocode-factory-rabbitmq-data:/var/lib/rabbitmq  

volumes:
  promocode-factory-administration-db-data:
  promocode-factory-receiving-from-partner-db-data:
  promocode-factory-giving-to-customer-db-data:
  promocode-factory-rabbitmq-data: